### ISSUE TITLE
bug  report

### ISSUE THREAD

**Issue by WeileiZeng** [guanyilun/wuhan_viz#2]
首页给了链接似乎有个多余的字符，发不开网站。

删掉以后可以打开网站。但是只有两个点，不是全国数据。觉得可以在网站上说明一下当前的数据状态。

**Comment by firslov** [comment]
1. readme里的链接应该没有问题，请问你是指哪里的链接？
2. 只有两个点是因为我为了避免地图较小时相近点重叠在一起，将显示点数量和缩放比例做了关联，当你放大地图时城市数量会增加。

**Comment by firslov** [comment]
1. readme里的链接应该没有问题，请问你是指哪里的链接？
2. 只有两个点是因为我为了避免地图较小时相近点重叠在一起，将显示点数量和缩放比例做了关联，当你放大地图时城市数量会增加。

> 首页给了链接似乎有个多余的字符，发不开网站。
> 
> 删掉以后可以打开网站。但是只有两个点，不是全国数据。觉得可以在网站上说明一下当前的数据状态。



> 首页给了链接似乎有个多余的字符，发不开网站。
> 
> 删掉以后可以打开网站。但是只有两个点，不是全国数据。觉得可以在网站上说明一下当前的数据状态。

1. readme里的链接应该没有问题，请问你是指哪里的链接？
2. 只有两个点是因为我为了避免地图较小时相近点重叠在一起，将显示点数量和缩放比例做了关联，当你放大地图时城市数量会增加。

**Comment by firslov** [comment]
> 首页给了链接似乎有个多余的字符，发不开网站。
> 
> 删掉以后可以打开网站。但是只有两个点，不是全国数据。觉得可以在网站上说明一下当前的数据状态。

1. readme里的链接应该没有问题，请问你是指哪里的链接？
2. 只有两个点是因为我为了避免地图较小时相近点重叠在一起，将显示点数量和缩放比例做了关联，当你放大地图时城市数量会增加。

**Comment by WeileiZeng** [comment]
抱歉没说清楚。不是readme。是github首页上方的一句简介和链接

**Comment by guanyilun** [comment]
感谢! 链接已修复
